disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Development With Michael"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "Michael Game Dev Logo 100x1000.png"

  [params.author]
  name = "Michael"
  email = "site@michaelgame.dev"
  # image = "img/blowfish_logo.png"
  imageQuality = 96
  headline = "Just a guy trying to get better at programming"

    [[params.author.links]]
    email = "mailto:site@michaelgame.dev"

    [[params.author.links]]
    link = "https://michaelgame.dev/"

    [[params.author.links]]
    github = "https://github.com/michaelgame-dev"

    [[params.author.links]]
    steam = "https://store.steampowered.com/app/2693660/Radiant_Bricks/"

    [[params.author.links]]
    twitch = "https://twitch.tv/michaelgame_dev"

    [[params.author.links]]
    x-twitter = "https://twitter.com/michaelgame_dev"

    [[params.author.links]]
    youtube = "https://youtube.com/@michaelgame_dev"

["params.author"]
image = "Michael Game Dev Logo 100x1000.png"
